services:
  - type: web
    name: linebot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: xxx
      - key: LINE_CHANNEL_SECRET
        value: yyy